ConcurrentWitness2Test/start.sh svcomp23-witness-benchmarks/tools/deagle/pthread-ext/25_stack_longer-2.yml/25_stack_longer-2.i --graphml-witness svcomp23-witness-benchmarks/tools/deagle/pthread-ext/25_stack_longer-2.yml/witness.graphml


--------------------------------------------------------------------------------


Traceback (most recent call last):
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/main.py", line 65, in translate_to_c
    result = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1796, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable
/tmp/BenchExec_run_oroe6z29/tmp/tmpt04qkcv1.c
Compilation started
Verdict: Unknown error
